### ISSUE TITLE
Entrega Desafio Vinicius Floriano

### ISSUE THREAD

**Issue by vinifloriano** [devMozao/desafio-reactjs#1]
Antes de tudo gostaria de parabenizar por essa atitude e por esse desafio, aprendi muito durante o processo de construção e creio que não fui o único, uma ótima forma de animar a galera.

Segue o link para o meu repositório com o app, fiz algumas alterações no design:
[app](https://github.com/ViniciusFloriano/desafio-reactjs/tree/viniciusfloriano/app)

Caso queira entrar em contato, por favor me chame no [linkedin](https://www.linkedin.com/in/vinifloriano/)

Adoraria receber um feedback e comecei a te seguir para todas as novidades.

Abraços,
Vinicius Floriano

**Comment by vivianedias** [comment]
Olá, @ViniciusFloriano! 

Muito massa seu repo :) Já dei uma olhada e parece show. 

Uma sugestão que iria fazer para facilitar o processo de nós devs que vamos fazer os Code Reviews, é você abrir um PR aqui pra esse repositório.  [Aqui](https://blog.tiagopariz.com/github-criando-um-fork-e-enviando-um-pull-request/) tem um artigo explicando como fazer - é super simples! A parte difícil você já deu conta hahah

Fazendo esse PR fica mais fácil da gente comentar e sugerir melhorias em partes específicas do seu código :) É isso, valeu! 👍🏾

**Comment by devmozao** [comment]
Code review feito e feedback realizados em call com o Vinicius. Fechando a issue.
