### ISSUE TITLE
Desafio React - AndradeIgor

### ISSUE THREAD

**Issue by andradeigor** [devMozao/desafio-reactjs#10]
Boa noite, segue o link: https://github.com/andradeigor/desafio-react

Agradeço muito pela ajuda dada até aqui e aguardo pelo retorno <3

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado via conferência. 😁
