### ISSUE TITLE
Desafio do mozão 

### ISSUE THREAD

**Issue by nathanlucena** [devMozao/desafio-reactjs#11]
Aqui tá o meu código Mozão: https://github.com/nathanlucena/desafio-reactjs

Eu nunca tinha alterado um read.me antes, então o meu não passa de uma copia descarada do marcusjava

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Opa meu caro. Acho que vc teve um imprevisto. Caso queira remarcar pra outra data, fique à vontade.

**Comment by nathanlucena** [comment]
Mozao, mil perdões cara recentemente comecei tomar remédios para ansiedade
e ataques de Pânico, hoje foi minha primeira crise pós remédio e não sabia
que ele ia me apagar por tanto tempo.
Tudo bem se não der pra você em outro momento, obrigado pela oportunidade

Em ter, 8 de jun de 2021 20:20, Diogo Fonseca ***@***.***>
escreveu:

**Comment by devmozao** [comment]
Opa meu caro! Espero que vc esteja bem! Fica à vontade pra remarcar pra um outro horário, não tem problema.

**Comment by devmozao** [comment]
feedback realizado em call no google meet. =D
