### ISSUE TITLE
Desafio ReactJs 

### ISSUE THREAD

**Issue by evertoont** [devMozao/desafio-reactjs#12]
Boa noite, 
Antes de mais nada, quero agradecer por esse desafio. Aprendi bastante coisa no meio do processo e gostaria muito de ter um code review, pois sei que tenho muita coisa para melhorar.

Segue o link do repositório: https://github.com/evertoont/desafio-reactjs

Desde já, agradeço!!

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
feedback realizado via conferência! 😁
