### ISSUE TITLE
Desafio reactJS

### ISSUE THREAD

**Issue by isaiasluc** [devMozao/desafio-reactjs#13]
https://github.com/isaiasluc/desafio-reactjs/tree/develop

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
feedback realizado em conferência no meet 😁
