### ISSUE TITLE
Desafio React 

### ISSUE THREAD

**Issue by fernanduandrade** [devMozao/desafio-reactjs#14]
Boa tarde 💜💜 segue o link do meu repositório  https://github.com/fernanduandrade/desafio-reactjs
Não sou frontend mas gostei muito de fazer o desafio, aprendi muito. 💜💜

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado por conferência no meet. xD
