### ISSUE TITLE
Entrega do desafio

### ISSUE THREAD

**Issue by mafeal** [devMozao/desafio-reactjs#15]
Diogo, segue a minha proposta de código para o seu desafio.
Agradeço muito a oportunidade, pois estou começando meio velho (44 anos) no desenvolvimento e estou agarrando todas as oportunidades de crescimento pessoal e profissional.
Parabéns pela iniciativa.
Segue o link para o código:

[Desafio-React](https://github.com/mafeal/desafio-reactjs/tree/my_proposal)

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs
