### ISSUE TITLE
Entrega do desafio

### ISSUE THREAD

**Issue by victordantasdev** [devMozao/desafio-reactjs#16]
Aqui está o [link](https://github.com/joaovictordantasj/SearchDevs) para o projeto, aguardo ansiosamente pelo code review. 
Muito obrigado pela oportunidade Mozão, aprendi muitas coisas legais durante todo o processo de desenvolvimento.

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado via conferencia no meet. 😁
