### ISSUE TITLE
Desafio reactJS

### ISSUE THREAD

**Issue by Lucas-R** [devMozao/desafio-reactjs#18]
Entrega do desafio ReactJS

https://github.com/Lucas-R/desafio-reactjs/tree/Lucas-R

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs
