### ISSUE TITLE
Desafio ReactJS

### ISSUE THREAD

**Issue by vmamore** [devMozao/desafio-reactjs#19]
Fala mozão!!
Obrigado pela iniciativa.
Segue o projeto: https://github.com/vmamore/desafio-reactjs

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado por call no meeting. 😁
