### ISSUE TITLE
Desafio ReactJs

### ISSUE THREAD

**Issue by JOAOSC17** [devMozao/desafio-reactjs#20]
Segue o link abaixo e obrigado pelo desafio
https://github.com/JOAOSC17/joaosc17.github.io-desafio-reactjs

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado por call no meeting. 😁
