### ISSUE TITLE
[code review] Entrega do desafio

### ISSUE THREAD

**Issue by viniciuscondev** [devMozao/desafio-reactjs#3]
Olá,
gostaria de agradecer pela iniciativa, foi muito bacana fazer o desafio, aprendi muitas coisas e foi muito massa conseguir resolver os problemas que iam surgindo. Foi bem mais complexo do que parecia no primeiro momento hahaha.

Segue o link do repositório com o código: https://github.com/viniciuscondev/desafio-reactjs

Edit: não consegui colocar a tag de code review, fui procurar e parece que só quem é contribuidor do repositório consegue. Não sei se é isso mesmo ou só não consegui achar a forma certa de colocar

**Comment by devmozao** [comment]
Meu caro, fiz o review aqui do seu desafio. Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia. 

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado por call no Google Meet.
