### ISSUE TITLE
Entrega do desafio

### ISSUE THREAD

**Issue by guilhpupo** [devMozao/desafio-reactjs#5]
Fala Mozão!

Quando vi o desafio não tinha certeza se tinha capacidade para completa-lo ou não. Essa insegurança logo passou depois de lembrar que na na vida real a verdade é que nunca estamos prontos e os desafios (como este) nos empurram pra frente e nos deixam mais sábios.

Quero agradecer a iniciativa, estou entrando agora na comunidade e pelo pouco contato que tive me senti muito bem acolhido e esse desafio fez eu me sentir um pouco mais perto.

[Link do repo](https://github.com/guilhpupo/desafio-reactjs)

E até mais no Code Review! (Alias é meu primeiro, pega leve 🤣)

**Comment by devmozao** [comment]
Maninho, terminei o code review. Bora pro feedback? Só abrir o calendly abaixo e marcar o dia e horário que for melhor pra ti. Aí a gente recebe o invite pra conferência no Google Meet.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado em conferência.
