### ISSUE TITLE
Desafio ReactJs

### ISSUE THREAD

**Issue by marcusjava** [devMozao/desafio-reactjs#6]
Segue abaixo link e obrigado pelo desafio

https://github.com/marcusjava/gitprofile

**Comment by devmozao** [comment]
Meu caro, fiz o review aqui do seu desafio. Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs
