### ISSUE TITLE
Desafio Reactjs

### ISSUE THREAD

**Issue by Douglashbr** [devMozao/desafio-reactjs#7]
Boa noite,

Cara, primeiramente queria agradecer por esse desafio, há bastante tempo eu tinha desanimado do React, talvez por não ter conhecimento o suficiente para estudá-lo na época, mas com esse desafio eu consegui aprender muito e vi que da pra seguir os estudos com ele.

Segue o link do repositório: https://github.com/Douglashbr/desafio-reactjs

Aguardo ansioso pelo code review kk.

Valeu, 
Abraços.

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs

**Comment by devmozao** [comment]
Feedback realizado via conferência. ༼ つ ◕_◕ ༽つ
