### ISSUE TITLE
Desafio ReactJs

### ISSUE THREAD

**Issue by rlima-nogueira** [devMozao/desafio-reactjs#8]
https://github.com/rlima-nogueira/desafio-reactjs/tree/feature/desafio-react

#3

**Comment by devmozao** [comment]
Bora marcar a nossa conversa pro feedback? Marca um dia e horário bom pra ti na minha agenda, e vc já vai receber o invite com o link da reunião pro dia.

https://calendly.com/devdiogo/feedback-desafio-reactjs
